// File generated by FlutterFire CLI or manually configured.
// To regenerate with your actual Firebase project credentials, run:
//   dart pub global activate flutterfire_cli
//   flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // REPLACE THESE PLACEHOLDERS WITH YOUR FIREBASE PROJECT VALUES
  // OR RUN: flutterfire configure

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcbvUDMdqDltNmNtSmwtaSuTfIeACk4jo',
    appId: '1:578989815824:web:74295cda70fec0cbbb7295',
    messagingSenderId: '578989815824',
    projectId: 'flutter-app-38c45',
    authDomain: 'flutter-app-38c45.firebaseapp.com',
    storageBucket: 'flutter-app-38c45.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAynnVj1X1z7xRhfhE21QQeIhz-2dxIm8Y',
    appId: '1:578989815824:android:3fbf9b2b086d803dbb7295',
    messagingSenderId: '578989815824',
    projectId: 'flutter-app-38c45',
    storageBucket: 'flutter-app-38c45.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAknIGOA6UiknZlFAABxHjBVUaniqlmh1Q',
    appId: '1:578989815824:ios:31f9703c39d82d67bb7295',
    messagingSenderId: '578989815824',
    projectId: 'flutter-app-38c45',
    storageBucket: 'flutter-app-38c45.firebasestorage.app',
    iosClientId: '578989815824-2neea2gvme8na0bqa3b609b1tc2kqgjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSignup',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAknIGOA6UiknZlFAABxHjBVUaniqlmh1Q',
    appId: '1:578989815824:ios:31f9703c39d82d67bb7295',
    messagingSenderId: '578989815824',
    projectId: 'flutter-app-38c45',
    storageBucket: 'flutter-app-38c45.firebasestorage.app',
    iosClientId: '578989815824-2neea2gvme8na0bqa3b609b1tc2kqgjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcbvUDMdqDltNmNtSmwtaSuTfIeACk4jo',
    appId: '1:578989815824:web:67c2fb730952526cbb7295',
    messagingSenderId: '578989815824',
    projectId: 'flutter-app-38c45',
    authDomain: 'flutter-app-38c45.firebaseapp.com',
    storageBucket: 'flutter-app-38c45.firebasestorage.app',
  );
}
